name = "sea-game-app"
compatibility_date = "2024-08-15"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sea-game-app"
database_id = "a44b58d9-dd5c-4a37-b132-7bb1993abc67"
